// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cm_group_storages.proto
// Protobuf C++ Version: 5.29.2

#include "cm_group_storages.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace dfs {
namespace proto {
namespace cm_group_storages {

inline constexpr response_t_storage_t::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : ip_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        port_{0u},
        magic_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR response_t_storage_t::response_t_storage_t(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct response_t_storage_tDefaultTypeInternal {
  PROTOBUF_CONSTEXPR response_t_storage_tDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~response_t_storage_tDefaultTypeInternal() {}
  union {
    response_t_storage_t _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 response_t_storage_tDefaultTypeInternal _response_t_storage_t_default_instance_;

inline constexpr response_t::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : storages_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR response_t::response_t(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct response_tDefaultTypeInternal {
  PROTOBUF_CONSTEXPR response_tDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~response_tDefaultTypeInternal() {}
  union {
    response_t _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 response_tDefaultTypeInternal _response_t_default_instance_;
}  // namespace cm_group_storages
}  // namespace proto
}  // namespace dfs
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_cm_5fgroup_5fstorages_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_cm_5fgroup_5fstorages_2eproto = nullptr;
const ::uint32_t
    TableStruct_cm_5fgroup_5fstorages_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::dfs::proto::cm_group_storages::response_t_storage_t, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::dfs::proto::cm_group_storages::response_t_storage_t, _impl_.ip_),
        PROTOBUF_FIELD_OFFSET(::dfs::proto::cm_group_storages::response_t_storage_t, _impl_.port_),
        PROTOBUF_FIELD_OFFSET(::dfs::proto::cm_group_storages::response_t_storage_t, _impl_.magic_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::dfs::proto::cm_group_storages::response_t, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::dfs::proto::cm_group_storages::response_t, _impl_.storages_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::dfs::proto::cm_group_storages::response_t_storage_t)},
        {11, -1, -1, sizeof(::dfs::proto::cm_group_storages::response_t)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::dfs::proto::cm_group_storages::_response_t_storage_t_default_instance_._instance,
    &::dfs::proto::cm_group_storages::_response_t_default_instance_._instance,
};
const char descriptor_table_protodef_cm_5fgroup_5fstorages_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\027cm_group_storages.proto\022\033dfs.proto.cm_"
    "group_storages\"\207\001\n\nresponse_t\022C\n\010storage"
    "s\030\001 \003(\01321.dfs.proto.cm_group_storages.re"
    "sponse_t.storage_t\0324\n\tstorage_t\022\n\n\002ip\030\001 "
    "\001(\t\022\014\n\004port\030\002 \001(\r\022\r\n\005magic\030\003 \001(\rb\006proto3"
};
static ::absl::once_flag descriptor_table_cm_5fgroup_5fstorages_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_cm_5fgroup_5fstorages_2eproto = {
    false,
    false,
    200,
    descriptor_table_protodef_cm_5fgroup_5fstorages_2eproto,
    "cm_group_storages.proto",
    &descriptor_table_cm_5fgroup_5fstorages_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_cm_5fgroup_5fstorages_2eproto::offsets,
    file_level_enum_descriptors_cm_5fgroup_5fstorages_2eproto,
    file_level_service_descriptors_cm_5fgroup_5fstorages_2eproto,
};
namespace dfs {
namespace proto {
namespace cm_group_storages {
// ===================================================================

class response_t_storage_t::_Internal {
 public:
};

response_t_storage_t::response_t_storage_t(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:dfs.proto.cm_group_storages.response_t.storage_t)
}
inline PROTOBUF_NDEBUG_INLINE response_t_storage_t::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::dfs::proto::cm_group_storages::response_t_storage_t& from_msg)
      : ip_(arena, from.ip_),
        _cached_size_{0} {}

response_t_storage_t::response_t_storage_t(
    ::google::protobuf::Arena* arena,
    const response_t_storage_t& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  response_t_storage_t* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, port_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, port_),
           offsetof(Impl_, magic_) -
               offsetof(Impl_, port_) +
               sizeof(Impl_::magic_));

  // @@protoc_insertion_point(copy_constructor:dfs.proto.cm_group_storages.response_t.storage_t)
}
inline PROTOBUF_NDEBUG_INLINE response_t_storage_t::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : ip_(arena),
        _cached_size_{0} {}

inline void response_t_storage_t::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, port_),
           0,
           offsetof(Impl_, magic_) -
               offsetof(Impl_, port_) +
               sizeof(Impl_::magic_));
}
response_t_storage_t::~response_t_storage_t() {
  // @@protoc_insertion_point(destructor:dfs.proto.cm_group_storages.response_t.storage_t)
  SharedDtor(*this);
}
inline void response_t_storage_t::SharedDtor(MessageLite& self) {
  response_t_storage_t& this_ = static_cast<response_t_storage_t&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.ip_.Destroy();
  this_._impl_.~Impl_();
}

inline void* response_t_storage_t::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) response_t_storage_t(arena);
}
constexpr auto response_t_storage_t::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(response_t_storage_t),
                                            alignof(response_t_storage_t));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull response_t_storage_t::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_response_t_storage_t_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &response_t_storage_t::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<response_t_storage_t>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &response_t_storage_t::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<response_t_storage_t>(), &response_t_storage_t::ByteSizeLong,
            &response_t_storage_t::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(response_t_storage_t, _impl_._cached_size_),
        false,
    },
    &response_t_storage_t::kDescriptorMethods,
    &descriptor_table_cm_5fgroup_5fstorages_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* response_t_storage_t::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 59, 2> response_t_storage_t::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::dfs::proto::cm_group_storages::response_t_storage_t>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string ip = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(response_t_storage_t, _impl_.ip_)}},
    // uint32 port = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(response_t_storage_t, _impl_.port_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(response_t_storage_t, _impl_.port_)}},
    // uint32 magic = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(response_t_storage_t, _impl_.magic_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(response_t_storage_t, _impl_.magic_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string ip = 1;
    {PROTOBUF_FIELD_OFFSET(response_t_storage_t, _impl_.ip_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 port = 2;
    {PROTOBUF_FIELD_OFFSET(response_t_storage_t, _impl_.port_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 magic = 3;
    {PROTOBUF_FIELD_OFFSET(response_t_storage_t, _impl_.magic_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
    "\60\2\0\0\0\0\0\0"
    "dfs.proto.cm_group_storages.response_t.storage_t"
    "ip"
  }},
};

PROTOBUF_NOINLINE void response_t_storage_t::Clear() {
// @@protoc_insertion_point(message_clear_start:dfs.proto.cm_group_storages.response_t.storage_t)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ip_.ClearToEmpty();
  ::memset(&_impl_.port_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.magic_) -
      reinterpret_cast<char*>(&_impl_.port_)) + sizeof(_impl_.magic_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* response_t_storage_t::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const response_t_storage_t& this_ = static_cast<const response_t_storage_t&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* response_t_storage_t::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const response_t_storage_t& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:dfs.proto.cm_group_storages.response_t.storage_t)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string ip = 1;
          if (!this_._internal_ip().empty()) {
            const std::string& _s = this_._internal_ip();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "dfs.proto.cm_group_storages.response_t.storage_t.ip");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // uint32 port = 2;
          if (this_._internal_port() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_port(), target);
          }

          // uint32 magic = 3;
          if (this_._internal_magic() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                3, this_._internal_magic(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:dfs.proto.cm_group_storages.response_t.storage_t)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t response_t_storage_t::ByteSizeLong(const MessageLite& base) {
          const response_t_storage_t& this_ = static_cast<const response_t_storage_t&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t response_t_storage_t::ByteSizeLong() const {
          const response_t_storage_t& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:dfs.proto.cm_group_storages.response_t.storage_t)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string ip = 1;
            if (!this_._internal_ip().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_ip());
            }
            // uint32 port = 2;
            if (this_._internal_port() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_port());
            }
            // uint32 magic = 3;
            if (this_._internal_magic() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_magic());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void response_t_storage_t::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<response_t_storage_t*>(&to_msg);
  auto& from = static_cast<const response_t_storage_t&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dfs.proto.cm_group_storages.response_t.storage_t)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_ip().empty()) {
    _this->_internal_set_ip(from._internal_ip());
  }
  if (from._internal_port() != 0) {
    _this->_impl_.port_ = from._impl_.port_;
  }
  if (from._internal_magic() != 0) {
    _this->_impl_.magic_ = from._impl_.magic_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void response_t_storage_t::CopyFrom(const response_t_storage_t& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dfs.proto.cm_group_storages.response_t.storage_t)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void response_t_storage_t::InternalSwap(response_t_storage_t* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ip_, &other->_impl_.ip_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(response_t_storage_t, _impl_.magic_)
      + sizeof(response_t_storage_t::_impl_.magic_)
      - PROTOBUF_FIELD_OFFSET(response_t_storage_t, _impl_.port_)>(
          reinterpret_cast<char*>(&_impl_.port_),
          reinterpret_cast<char*>(&other->_impl_.port_));
}

::google::protobuf::Metadata response_t_storage_t::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class response_t::_Internal {
 public:
};

response_t::response_t(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:dfs.proto.cm_group_storages.response_t)
}
inline PROTOBUF_NDEBUG_INLINE response_t::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::dfs::proto::cm_group_storages::response_t& from_msg)
      : storages_{visibility, arena, from.storages_},
        _cached_size_{0} {}

response_t::response_t(
    ::google::protobuf::Arena* arena,
    const response_t& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  response_t* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:dfs.proto.cm_group_storages.response_t)
}
inline PROTOBUF_NDEBUG_INLINE response_t::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : storages_{visibility, arena},
        _cached_size_{0} {}

inline void response_t::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
response_t::~response_t() {
  // @@protoc_insertion_point(destructor:dfs.proto.cm_group_storages.response_t)
  SharedDtor(*this);
}
inline void response_t::SharedDtor(MessageLite& self) {
  response_t& this_ = static_cast<response_t&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* response_t::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) response_t(arena);
}
constexpr auto response_t::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(response_t, _impl_.storages_) +
          decltype(response_t::_impl_.storages_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(response_t), alignof(response_t), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&response_t::PlacementNew_,
                                 sizeof(response_t),
                                 alignof(response_t));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull response_t::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_response_t_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &response_t::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<response_t>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &response_t::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<response_t>(), &response_t::ByteSizeLong,
            &response_t::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(response_t, _impl_._cached_size_),
        false,
    },
    &response_t::kDescriptorMethods,
    &descriptor_table_cm_5fgroup_5fstorages_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* response_t::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> response_t::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::dfs::proto::cm_group_storages::response_t>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .dfs.proto.cm_group_storages.response_t.storage_t storages = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(response_t, _impl_.storages_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .dfs.proto.cm_group_storages.response_t.storage_t storages = 1;
    {PROTOBUF_FIELD_OFFSET(response_t, _impl_.storages_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::dfs::proto::cm_group_storages::response_t_storage_t>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void response_t::Clear() {
// @@protoc_insertion_point(message_clear_start:dfs.proto.cm_group_storages.response_t)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.storages_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* response_t::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const response_t& this_ = static_cast<const response_t&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* response_t::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const response_t& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:dfs.proto.cm_group_storages.response_t)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .dfs.proto.cm_group_storages.response_t.storage_t storages = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_storages_size());
               i < n; i++) {
            const auto& repfield = this_._internal_storages().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:dfs.proto.cm_group_storages.response_t)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t response_t::ByteSizeLong(const MessageLite& base) {
          const response_t& this_ = static_cast<const response_t&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t response_t::ByteSizeLong() const {
          const response_t& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:dfs.proto.cm_group_storages.response_t)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .dfs.proto.cm_group_storages.response_t.storage_t storages = 1;
            {
              total_size += 1UL * this_._internal_storages_size();
              for (const auto& msg : this_._internal_storages()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void response_t::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<response_t*>(&to_msg);
  auto& from = static_cast<const response_t&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dfs.proto.cm_group_storages.response_t)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_storages()->MergeFrom(
      from._internal_storages());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void response_t::CopyFrom(const response_t& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dfs.proto.cm_group_storages.response_t)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void response_t::InternalSwap(response_t* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.storages_.InternalSwap(&other->_impl_.storages_);
}

::google::protobuf::Metadata response_t::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace cm_group_storages
}  // namespace proto
}  // namespace dfs
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_cm_5fgroup_5fstorages_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
