// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cm_group_storages.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_cm_5fgroup_5fstorages_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_cm_5fgroup_5fstorages_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_cm_5fgroup_5fstorages_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_cm_5fgroup_5fstorages_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_cm_5fgroup_5fstorages_2eproto;
namespace dfs {
namespace proto {
namespace cm_group_storages {
class response_t;
struct response_tDefaultTypeInternal;
extern response_tDefaultTypeInternal _response_t_default_instance_;
class response_t_storage_t;
struct response_t_storage_tDefaultTypeInternal;
extern response_t_storage_tDefaultTypeInternal _response_t_storage_t_default_instance_;
}  // namespace cm_group_storages
}  // namespace proto
}  // namespace dfs
PROTOBUF_NAMESPACE_OPEN
template<> ::dfs::proto::cm_group_storages::response_t* Arena::CreateMaybeMessage<::dfs::proto::cm_group_storages::response_t>(Arena*);
template<> ::dfs::proto::cm_group_storages::response_t_storage_t* Arena::CreateMaybeMessage<::dfs::proto::cm_group_storages::response_t_storage_t>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace dfs {
namespace proto {
namespace cm_group_storages {

// ===================================================================

class response_t_storage_t final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dfs.proto.cm_group_storages.response_t.storage_t) */ {
 public:
  inline response_t_storage_t() : response_t_storage_t(nullptr) {}
  ~response_t_storage_t() override;
  explicit PROTOBUF_CONSTEXPR response_t_storage_t(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  response_t_storage_t(const response_t_storage_t& from);
  response_t_storage_t(response_t_storage_t&& from) noexcept
    : response_t_storage_t() {
    *this = ::std::move(from);
  }

  inline response_t_storage_t& operator=(const response_t_storage_t& from) {
    CopyFrom(from);
    return *this;
  }
  inline response_t_storage_t& operator=(response_t_storage_t&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const response_t_storage_t& default_instance() {
    return *internal_default_instance();
  }
  static inline const response_t_storage_t* internal_default_instance() {
    return reinterpret_cast<const response_t_storage_t*>(
               &_response_t_storage_t_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(response_t_storage_t& a, response_t_storage_t& b) {
    a.Swap(&b);
  }
  inline void Swap(response_t_storage_t* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(response_t_storage_t* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  response_t_storage_t* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<response_t_storage_t>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const response_t_storage_t& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const response_t_storage_t& from) {
    response_t_storage_t::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(response_t_storage_t* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "dfs.proto.cm_group_storages.response_t.storage_t";
  }
  protected:
  explicit response_t_storage_t(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIpFieldNumber = 1,
    kPortFieldNumber = 2,
    kMagicFieldNumber = 3,
  };
  // string ip = 1;
  void clear_ip();
  const std::string& ip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ip();
  PROTOBUF_NODISCARD std::string* release_ip();
  void set_allocated_ip(std::string* ip);
  private:
  const std::string& _internal_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ip(const std::string& value);
  std::string* _internal_mutable_ip();
  public:

  // uint32 port = 2;
  void clear_port();
  uint32_t port() const;
  void set_port(uint32_t value);
  private:
  uint32_t _internal_port() const;
  void _internal_set_port(uint32_t value);
  public:

  // uint32 magic = 3;
  void clear_magic();
  uint32_t magic() const;
  void set_magic(uint32_t value);
  private:
  uint32_t _internal_magic() const;
  void _internal_set_magic(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:dfs.proto.cm_group_storages.response_t.storage_t)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ip_;
    uint32_t port_;
    uint32_t magic_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cm_5fgroup_5fstorages_2eproto;
};
// -------------------------------------------------------------------

class response_t final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dfs.proto.cm_group_storages.response_t) */ {
 public:
  inline response_t() : response_t(nullptr) {}
  ~response_t() override;
  explicit PROTOBUF_CONSTEXPR response_t(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  response_t(const response_t& from);
  response_t(response_t&& from) noexcept
    : response_t() {
    *this = ::std::move(from);
  }

  inline response_t& operator=(const response_t& from) {
    CopyFrom(from);
    return *this;
  }
  inline response_t& operator=(response_t&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const response_t& default_instance() {
    return *internal_default_instance();
  }
  static inline const response_t* internal_default_instance() {
    return reinterpret_cast<const response_t*>(
               &_response_t_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(response_t& a, response_t& b) {
    a.Swap(&b);
  }
  inline void Swap(response_t* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(response_t* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  response_t* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<response_t>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const response_t& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const response_t& from) {
    response_t::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(response_t* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "dfs.proto.cm_group_storages.response_t";
  }
  protected:
  explicit response_t(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef response_t_storage_t storage_t;

  // accessors -------------------------------------------------------

  enum : int {
    kStoragesFieldNumber = 1,
  };
  // repeated .dfs.proto.cm_group_storages.response_t.storage_t storages = 1;
  int storages_size() const;
  private:
  int _internal_storages_size() const;
  public:
  void clear_storages();
  ::dfs::proto::cm_group_storages::response_t_storage_t* mutable_storages(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dfs::proto::cm_group_storages::response_t_storage_t >*
      mutable_storages();
  private:
  const ::dfs::proto::cm_group_storages::response_t_storage_t& _internal_storages(int index) const;
  ::dfs::proto::cm_group_storages::response_t_storage_t* _internal_add_storages();
  public:
  const ::dfs::proto::cm_group_storages::response_t_storage_t& storages(int index) const;
  ::dfs::proto::cm_group_storages::response_t_storage_t* add_storages();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dfs::proto::cm_group_storages::response_t_storage_t >&
      storages() const;

  // @@protoc_insertion_point(class_scope:dfs.proto.cm_group_storages.response_t)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dfs::proto::cm_group_storages::response_t_storage_t > storages_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cm_5fgroup_5fstorages_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// response_t_storage_t

// string ip = 1;
inline void response_t_storage_t::clear_ip() {
  _impl_.ip_.ClearToEmpty();
}
inline const std::string& response_t_storage_t::ip() const {
  // @@protoc_insertion_point(field_get:dfs.proto.cm_group_storages.response_t.storage_t.ip)
  return _internal_ip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void response_t_storage_t::set_ip(ArgT0&& arg0, ArgT... args) {
 
 _impl_.ip_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:dfs.proto.cm_group_storages.response_t.storage_t.ip)
}
inline std::string* response_t_storage_t::mutable_ip() {
  std::string* _s = _internal_mutable_ip();
  // @@protoc_insertion_point(field_mutable:dfs.proto.cm_group_storages.response_t.storage_t.ip)
  return _s;
}
inline const std::string& response_t_storage_t::_internal_ip() const {
  return _impl_.ip_.Get();
}
inline void response_t_storage_t::_internal_set_ip(const std::string& value) {
  
  _impl_.ip_.Set(value, GetArenaForAllocation());
}
inline std::string* response_t_storage_t::_internal_mutable_ip() {
  
  return _impl_.ip_.Mutable(GetArenaForAllocation());
}
inline std::string* response_t_storage_t::release_ip() {
  // @@protoc_insertion_point(field_release:dfs.proto.cm_group_storages.response_t.storage_t.ip)
  return _impl_.ip_.Release();
}
inline void response_t_storage_t::set_allocated_ip(std::string* ip) {
  if (ip != nullptr) {
    
  } else {
    
  }
  _impl_.ip_.SetAllocated(ip, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ip_.IsDefault()) {
    _impl_.ip_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:dfs.proto.cm_group_storages.response_t.storage_t.ip)
}

// uint32 port = 2;
inline void response_t_storage_t::clear_port() {
  _impl_.port_ = 0u;
}
inline uint32_t response_t_storage_t::_internal_port() const {
  return _impl_.port_;
}
inline uint32_t response_t_storage_t::port() const {
  // @@protoc_insertion_point(field_get:dfs.proto.cm_group_storages.response_t.storage_t.port)
  return _internal_port();
}
inline void response_t_storage_t::_internal_set_port(uint32_t value) {
  
  _impl_.port_ = value;
}
inline void response_t_storage_t::set_port(uint32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:dfs.proto.cm_group_storages.response_t.storage_t.port)
}

// uint32 magic = 3;
inline void response_t_storage_t::clear_magic() {
  _impl_.magic_ = 0u;
}
inline uint32_t response_t_storage_t::_internal_magic() const {
  return _impl_.magic_;
}
inline uint32_t response_t_storage_t::magic() const {
  // @@protoc_insertion_point(field_get:dfs.proto.cm_group_storages.response_t.storage_t.magic)
  return _internal_magic();
}
inline void response_t_storage_t::_internal_set_magic(uint32_t value) {
  
  _impl_.magic_ = value;
}
inline void response_t_storage_t::set_magic(uint32_t value) {
  _internal_set_magic(value);
  // @@protoc_insertion_point(field_set:dfs.proto.cm_group_storages.response_t.storage_t.magic)
}

// -------------------------------------------------------------------

// response_t

// repeated .dfs.proto.cm_group_storages.response_t.storage_t storages = 1;
inline int response_t::_internal_storages_size() const {
  return _impl_.storages_.size();
}
inline int response_t::storages_size() const {
  return _internal_storages_size();
}
inline void response_t::clear_storages() {
  _impl_.storages_.Clear();
}
inline ::dfs::proto::cm_group_storages::response_t_storage_t* response_t::mutable_storages(int index) {
  // @@protoc_insertion_point(field_mutable:dfs.proto.cm_group_storages.response_t.storages)
  return _impl_.storages_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dfs::proto::cm_group_storages::response_t_storage_t >*
response_t::mutable_storages() {
  // @@protoc_insertion_point(field_mutable_list:dfs.proto.cm_group_storages.response_t.storages)
  return &_impl_.storages_;
}
inline const ::dfs::proto::cm_group_storages::response_t_storage_t& response_t::_internal_storages(int index) const {
  return _impl_.storages_.Get(index);
}
inline const ::dfs::proto::cm_group_storages::response_t_storage_t& response_t::storages(int index) const {
  // @@protoc_insertion_point(field_get:dfs.proto.cm_group_storages.response_t.storages)
  return _internal_storages(index);
}
inline ::dfs::proto::cm_group_storages::response_t_storage_t* response_t::_internal_add_storages() {
  return _impl_.storages_.Add();
}
inline ::dfs::proto::cm_group_storages::response_t_storage_t* response_t::add_storages() {
  ::dfs::proto::cm_group_storages::response_t_storage_t* _add = _internal_add_storages();
  // @@protoc_insertion_point(field_add:dfs.proto.cm_group_storages.response_t.storages)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::dfs::proto::cm_group_storages::response_t_storage_t >&
response_t::storages() const {
  // @@protoc_insertion_point(field_list:dfs.proto.cm_group_storages.response_t.storages)
  return _impl_.storages_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace cm_group_storages
}  // namespace proto
}  // namespace dfs

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_cm_5fgroup_5fstorages_2eproto
