// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cm_valid_storage.proto
// Protobuf C++ Version: 5.29.2

#ifndef cm_5fvalid_5fstorage_2eproto_2epb_2eh
#define cm_5fvalid_5fstorage_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_cm_5fvalid_5fstorage_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_cm_5fvalid_5fstorage_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_cm_5fvalid_5fstorage_2eproto;
namespace dfs {
namespace proto {
namespace cm_valid_storage {
class response_t;
struct response_tDefaultTypeInternal;
extern response_tDefaultTypeInternal _response_t_default_instance_;
}  // namespace cm_valid_storage
}  // namespace proto
}  // namespace dfs
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace dfs {
namespace proto {
namespace cm_valid_storage {

// ===================================================================


// -------------------------------------------------------------------

class response_t final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:dfs.proto.cm_valid_storage.response_t) */ {
 public:
  inline response_t() : response_t(nullptr) {}
  ~response_t() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(response_t* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(response_t));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR response_t(
      ::google::protobuf::internal::ConstantInitialized);

  inline response_t(const response_t& from) : response_t(nullptr, from) {}
  inline response_t(response_t&& from) noexcept
      : response_t(nullptr, std::move(from)) {}
  inline response_t& operator=(const response_t& from) {
    CopyFrom(from);
    return *this;
  }
  inline response_t& operator=(response_t&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const response_t& default_instance() {
    return *internal_default_instance();
  }
  static inline const response_t* internal_default_instance() {
    return reinterpret_cast<const response_t*>(
        &_response_t_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(response_t& a, response_t& b) { a.Swap(&b); }
  inline void Swap(response_t* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(response_t* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  response_t* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<response_t>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const response_t& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const response_t& from) { response_t::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(response_t* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "dfs.proto.cm_valid_storage.response_t"; }

 protected:
  explicit response_t(::google::protobuf::Arena* arena);
  response_t(::google::protobuf::Arena* arena, const response_t& from);
  response_t(::google::protobuf::Arena* arena, response_t&& from) noexcept
      : response_t(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStorageIpFieldNumber = 3,
    kStorageMagicFieldNumber = 1,
    kStoragePortFieldNumber = 2,
  };
  // string storage_ip = 3;
  void clear_storage_ip() ;
  const std::string& storage_ip() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_storage_ip(Arg_&& arg, Args_... args);
  std::string* mutable_storage_ip();
  PROTOBUF_NODISCARD std::string* release_storage_ip();
  void set_allocated_storage_ip(std::string* value);

  private:
  const std::string& _internal_storage_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_storage_ip(
      const std::string& value);
  std::string* _internal_mutable_storage_ip();

  public:
  // uint32 storage_magic = 1;
  void clear_storage_magic() ;
  ::uint32_t storage_magic() const;
  void set_storage_magic(::uint32_t value);

  private:
  ::uint32_t _internal_storage_magic() const;
  void _internal_set_storage_magic(::uint32_t value);

  public:
  // uint32 storage_port = 2;
  void clear_storage_port() ;
  ::uint32_t storage_port() const;
  void set_storage_port(::uint32_t value);

  private:
  ::uint32_t _internal_storage_port() const;
  void _internal_set_storage_port(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:dfs.proto.cm_valid_storage.response_t)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      56, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const response_t& from_msg);
    ::google::protobuf::internal::ArenaStringPtr storage_ip_;
    ::uint32_t storage_magic_;
    ::uint32_t storage_port_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cm_5fvalid_5fstorage_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// response_t

// uint32 storage_magic = 1;
inline void response_t::clear_storage_magic() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.storage_magic_ = 0u;
}
inline ::uint32_t response_t::storage_magic() const {
  // @@protoc_insertion_point(field_get:dfs.proto.cm_valid_storage.response_t.storage_magic)
  return _internal_storage_magic();
}
inline void response_t::set_storage_magic(::uint32_t value) {
  _internal_set_storage_magic(value);
  // @@protoc_insertion_point(field_set:dfs.proto.cm_valid_storage.response_t.storage_magic)
}
inline ::uint32_t response_t::_internal_storage_magic() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.storage_magic_;
}
inline void response_t::_internal_set_storage_magic(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.storage_magic_ = value;
}

// uint32 storage_port = 2;
inline void response_t::clear_storage_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.storage_port_ = 0u;
}
inline ::uint32_t response_t::storage_port() const {
  // @@protoc_insertion_point(field_get:dfs.proto.cm_valid_storage.response_t.storage_port)
  return _internal_storage_port();
}
inline void response_t::set_storage_port(::uint32_t value) {
  _internal_set_storage_port(value);
  // @@protoc_insertion_point(field_set:dfs.proto.cm_valid_storage.response_t.storage_port)
}
inline ::uint32_t response_t::_internal_storage_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.storage_port_;
}
inline void response_t::_internal_set_storage_port(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.storage_port_ = value;
}

// string storage_ip = 3;
inline void response_t::clear_storage_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.storage_ip_.ClearToEmpty();
}
inline const std::string& response_t::storage_ip() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:dfs.proto.cm_valid_storage.response_t.storage_ip)
  return _internal_storage_ip();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void response_t::set_storage_ip(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.storage_ip_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:dfs.proto.cm_valid_storage.response_t.storage_ip)
}
inline std::string* response_t::mutable_storage_ip() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_storage_ip();
  // @@protoc_insertion_point(field_mutable:dfs.proto.cm_valid_storage.response_t.storage_ip)
  return _s;
}
inline const std::string& response_t::_internal_storage_ip() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.storage_ip_.Get();
}
inline void response_t::_internal_set_storage_ip(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.storage_ip_.Set(value, GetArena());
}
inline std::string* response_t::_internal_mutable_storage_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.storage_ip_.Mutable( GetArena());
}
inline std::string* response_t::release_storage_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:dfs.proto.cm_valid_storage.response_t.storage_ip)
  return _impl_.storage_ip_.Release();
}
inline void response_t::set_allocated_storage_ip(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.storage_ip_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.storage_ip_.IsDefault()) {
    _impl_.storage_ip_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:dfs.proto.cm_valid_storage.response_t.storage_ip)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace cm_valid_storage
}  // namespace proto
}  // namespace dfs


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // cm_5fvalid_5fstorage_2eproto_2epb_2eh
