// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cm_valid_storage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_cm_5fvalid_5fstorage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_cm_5fvalid_5fstorage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_cm_5fvalid_5fstorage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_cm_5fvalid_5fstorage_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_cm_5fvalid_5fstorage_2eproto;
namespace dfs {
namespace proto {
namespace cm_valid_storage {
class response_t;
struct response_tDefaultTypeInternal;
extern response_tDefaultTypeInternal _response_t_default_instance_;
}  // namespace cm_valid_storage
}  // namespace proto
}  // namespace dfs
PROTOBUF_NAMESPACE_OPEN
template<> ::dfs::proto::cm_valid_storage::response_t* Arena::CreateMaybeMessage<::dfs::proto::cm_valid_storage::response_t>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace dfs {
namespace proto {
namespace cm_valid_storage {

// ===================================================================

class response_t final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dfs.proto.cm_valid_storage.response_t) */ {
 public:
  inline response_t() : response_t(nullptr) {}
  ~response_t() override;
  explicit PROTOBUF_CONSTEXPR response_t(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  response_t(const response_t& from);
  response_t(response_t&& from) noexcept
    : response_t() {
    *this = ::std::move(from);
  }

  inline response_t& operator=(const response_t& from) {
    CopyFrom(from);
    return *this;
  }
  inline response_t& operator=(response_t&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const response_t& default_instance() {
    return *internal_default_instance();
  }
  static inline const response_t* internal_default_instance() {
    return reinterpret_cast<const response_t*>(
               &_response_t_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(response_t& a, response_t& b) {
    a.Swap(&b);
  }
  inline void Swap(response_t* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(response_t* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  response_t* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<response_t>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const response_t& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const response_t& from) {
    response_t::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(response_t* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "dfs.proto.cm_valid_storage.response_t";
  }
  protected:
  explicit response_t(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStorageIpFieldNumber = 3,
    kStorageMagicFieldNumber = 1,
    kStoragePortFieldNumber = 2,
  };
  // string storage_ip = 3;
  void clear_storage_ip();
  const std::string& storage_ip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_storage_ip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_storage_ip();
  PROTOBUF_NODISCARD std::string* release_storage_ip();
  void set_allocated_storage_ip(std::string* storage_ip);
  private:
  const std::string& _internal_storage_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_storage_ip(const std::string& value);
  std::string* _internal_mutable_storage_ip();
  public:

  // uint32 storage_magic = 1;
  void clear_storage_magic();
  uint32_t storage_magic() const;
  void set_storage_magic(uint32_t value);
  private:
  uint32_t _internal_storage_magic() const;
  void _internal_set_storage_magic(uint32_t value);
  public:

  // uint32 storage_port = 2;
  void clear_storage_port();
  uint32_t storage_port() const;
  void set_storage_port(uint32_t value);
  private:
  uint32_t _internal_storage_port() const;
  void _internal_set_storage_port(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:dfs.proto.cm_valid_storage.response_t)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr storage_ip_;
    uint32_t storage_magic_;
    uint32_t storage_port_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cm_5fvalid_5fstorage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// response_t

// uint32 storage_magic = 1;
inline void response_t::clear_storage_magic() {
  _impl_.storage_magic_ = 0u;
}
inline uint32_t response_t::_internal_storage_magic() const {
  return _impl_.storage_magic_;
}
inline uint32_t response_t::storage_magic() const {
  // @@protoc_insertion_point(field_get:dfs.proto.cm_valid_storage.response_t.storage_magic)
  return _internal_storage_magic();
}
inline void response_t::_internal_set_storage_magic(uint32_t value) {
  
  _impl_.storage_magic_ = value;
}
inline void response_t::set_storage_magic(uint32_t value) {
  _internal_set_storage_magic(value);
  // @@protoc_insertion_point(field_set:dfs.proto.cm_valid_storage.response_t.storage_magic)
}

// uint32 storage_port = 2;
inline void response_t::clear_storage_port() {
  _impl_.storage_port_ = 0u;
}
inline uint32_t response_t::_internal_storage_port() const {
  return _impl_.storage_port_;
}
inline uint32_t response_t::storage_port() const {
  // @@protoc_insertion_point(field_get:dfs.proto.cm_valid_storage.response_t.storage_port)
  return _internal_storage_port();
}
inline void response_t::_internal_set_storage_port(uint32_t value) {
  
  _impl_.storage_port_ = value;
}
inline void response_t::set_storage_port(uint32_t value) {
  _internal_set_storage_port(value);
  // @@protoc_insertion_point(field_set:dfs.proto.cm_valid_storage.response_t.storage_port)
}

// string storage_ip = 3;
inline void response_t::clear_storage_ip() {
  _impl_.storage_ip_.ClearToEmpty();
}
inline const std::string& response_t::storage_ip() const {
  // @@protoc_insertion_point(field_get:dfs.proto.cm_valid_storage.response_t.storage_ip)
  return _internal_storage_ip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void response_t::set_storage_ip(ArgT0&& arg0, ArgT... args) {
 
 _impl_.storage_ip_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:dfs.proto.cm_valid_storage.response_t.storage_ip)
}
inline std::string* response_t::mutable_storage_ip() {
  std::string* _s = _internal_mutable_storage_ip();
  // @@protoc_insertion_point(field_mutable:dfs.proto.cm_valid_storage.response_t.storage_ip)
  return _s;
}
inline const std::string& response_t::_internal_storage_ip() const {
  return _impl_.storage_ip_.Get();
}
inline void response_t::_internal_set_storage_ip(const std::string& value) {
  
  _impl_.storage_ip_.Set(value, GetArenaForAllocation());
}
inline std::string* response_t::_internal_mutable_storage_ip() {
  
  return _impl_.storage_ip_.Mutable(GetArenaForAllocation());
}
inline std::string* response_t::release_storage_ip() {
  // @@protoc_insertion_point(field_release:dfs.proto.cm_valid_storage.response_t.storage_ip)
  return _impl_.storage_ip_.Release();
}
inline void response_t::set_allocated_storage_ip(std::string* storage_ip) {
  if (storage_ip != nullptr) {
    
  } else {
    
  }
  _impl_.storage_ip_.SetAllocated(storage_ip, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.storage_ip_.IsDefault()) {
    _impl_.storage_ip_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:dfs.proto.cm_valid_storage.response_t.storage_ip)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace cm_valid_storage
}  // namespace proto
}  // namespace dfs

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_cm_5fvalid_5fstorage_2eproto
