// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cm_valid_storage.proto
// Protobuf C++ Version: 5.29.2

#include "cm_valid_storage.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace dfs {
namespace proto {
namespace cm_valid_storage {

inline constexpr response_t::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : storage_ip_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        storage_magic_{0u},
        storage_port_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR response_t::response_t(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct response_tDefaultTypeInternal {
  PROTOBUF_CONSTEXPR response_tDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~response_tDefaultTypeInternal() {}
  union {
    response_t _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 response_tDefaultTypeInternal _response_t_default_instance_;
}  // namespace cm_valid_storage
}  // namespace proto
}  // namespace dfs
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_cm_5fvalid_5fstorage_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_cm_5fvalid_5fstorage_2eproto = nullptr;
const ::uint32_t
    TableStruct_cm_5fvalid_5fstorage_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::dfs::proto::cm_valid_storage::response_t, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::dfs::proto::cm_valid_storage::response_t, _impl_.storage_magic_),
        PROTOBUF_FIELD_OFFSET(::dfs::proto::cm_valid_storage::response_t, _impl_.storage_port_),
        PROTOBUF_FIELD_OFFSET(::dfs::proto::cm_valid_storage::response_t, _impl_.storage_ip_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::dfs::proto::cm_valid_storage::response_t)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::dfs::proto::cm_valid_storage::_response_t_default_instance_._instance,
};
const char descriptor_table_protodef_cm_5fvalid_5fstorage_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\026cm_valid_storage.proto\022\032dfs.proto.cm_v"
    "alid_storage\"M\n\nresponse_t\022\025\n\rstorage_ma"
    "gic\030\001 \001(\r\022\024\n\014storage_port\030\002 \001(\r\022\022\n\nstora"
    "ge_ip\030\003 \001(\tb\006proto3"
};
static ::absl::once_flag descriptor_table_cm_5fvalid_5fstorage_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_cm_5fvalid_5fstorage_2eproto = {
    false,
    false,
    139,
    descriptor_table_protodef_cm_5fvalid_5fstorage_2eproto,
    "cm_valid_storage.proto",
    &descriptor_table_cm_5fvalid_5fstorage_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_cm_5fvalid_5fstorage_2eproto::offsets,
    file_level_enum_descriptors_cm_5fvalid_5fstorage_2eproto,
    file_level_service_descriptors_cm_5fvalid_5fstorage_2eproto,
};
namespace dfs {
namespace proto {
namespace cm_valid_storage {
// ===================================================================

class response_t::_Internal {
 public:
};

response_t::response_t(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:dfs.proto.cm_valid_storage.response_t)
}
inline PROTOBUF_NDEBUG_INLINE response_t::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::dfs::proto::cm_valid_storage::response_t& from_msg)
      : storage_ip_(arena, from.storage_ip_),
        _cached_size_{0} {}

response_t::response_t(
    ::google::protobuf::Arena* arena,
    const response_t& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  response_t* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, storage_magic_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, storage_magic_),
           offsetof(Impl_, storage_port_) -
               offsetof(Impl_, storage_magic_) +
               sizeof(Impl_::storage_port_));

  // @@protoc_insertion_point(copy_constructor:dfs.proto.cm_valid_storage.response_t)
}
inline PROTOBUF_NDEBUG_INLINE response_t::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : storage_ip_(arena),
        _cached_size_{0} {}

inline void response_t::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, storage_magic_),
           0,
           offsetof(Impl_, storage_port_) -
               offsetof(Impl_, storage_magic_) +
               sizeof(Impl_::storage_port_));
}
response_t::~response_t() {
  // @@protoc_insertion_point(destructor:dfs.proto.cm_valid_storage.response_t)
  SharedDtor(*this);
}
inline void response_t::SharedDtor(MessageLite& self) {
  response_t& this_ = static_cast<response_t&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.storage_ip_.Destroy();
  this_._impl_.~Impl_();
}

inline void* response_t::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) response_t(arena);
}
constexpr auto response_t::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(response_t),
                                            alignof(response_t));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull response_t::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_response_t_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &response_t::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<response_t>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &response_t::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<response_t>(), &response_t::ByteSizeLong,
            &response_t::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(response_t, _impl_._cached_size_),
        false,
    },
    &response_t::kDescriptorMethods,
    &descriptor_table_cm_5fvalid_5fstorage_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* response_t::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 56, 2> response_t::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::dfs::proto::cm_valid_storage::response_t>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 storage_magic = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(response_t, _impl_.storage_magic_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(response_t, _impl_.storage_magic_)}},
    // uint32 storage_port = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(response_t, _impl_.storage_port_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(response_t, _impl_.storage_port_)}},
    // string storage_ip = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(response_t, _impl_.storage_ip_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 storage_magic = 1;
    {PROTOBUF_FIELD_OFFSET(response_t, _impl_.storage_magic_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 storage_port = 2;
    {PROTOBUF_FIELD_OFFSET(response_t, _impl_.storage_port_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // string storage_ip = 3;
    {PROTOBUF_FIELD_OFFSET(response_t, _impl_.storage_ip_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\45\0\0\12\0\0\0\0"
    "dfs.proto.cm_valid_storage.response_t"
    "storage_ip"
  }},
};

PROTOBUF_NOINLINE void response_t::Clear() {
// @@protoc_insertion_point(message_clear_start:dfs.proto.cm_valid_storage.response_t)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.storage_ip_.ClearToEmpty();
  ::memset(&_impl_.storage_magic_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.storage_port_) -
      reinterpret_cast<char*>(&_impl_.storage_magic_)) + sizeof(_impl_.storage_port_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* response_t::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const response_t& this_ = static_cast<const response_t&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* response_t::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const response_t& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:dfs.proto.cm_valid_storage.response_t)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 storage_magic = 1;
          if (this_._internal_storage_magic() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_storage_magic(), target);
          }

          // uint32 storage_port = 2;
          if (this_._internal_storage_port() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_storage_port(), target);
          }

          // string storage_ip = 3;
          if (!this_._internal_storage_ip().empty()) {
            const std::string& _s = this_._internal_storage_ip();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "dfs.proto.cm_valid_storage.response_t.storage_ip");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:dfs.proto.cm_valid_storage.response_t)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t response_t::ByteSizeLong(const MessageLite& base) {
          const response_t& this_ = static_cast<const response_t&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t response_t::ByteSizeLong() const {
          const response_t& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:dfs.proto.cm_valid_storage.response_t)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string storage_ip = 3;
            if (!this_._internal_storage_ip().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_storage_ip());
            }
            // uint32 storage_magic = 1;
            if (this_._internal_storage_magic() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_storage_magic());
            }
            // uint32 storage_port = 2;
            if (this_._internal_storage_port() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_storage_port());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void response_t::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<response_t*>(&to_msg);
  auto& from = static_cast<const response_t&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dfs.proto.cm_valid_storage.response_t)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_storage_ip().empty()) {
    _this->_internal_set_storage_ip(from._internal_storage_ip());
  }
  if (from._internal_storage_magic() != 0) {
    _this->_impl_.storage_magic_ = from._impl_.storage_magic_;
  }
  if (from._internal_storage_port() != 0) {
    _this->_impl_.storage_port_ = from._impl_.storage_port_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void response_t::CopyFrom(const response_t& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dfs.proto.cm_valid_storage.response_t)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void response_t::InternalSwap(response_t* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.storage_ip_, &other->_impl_.storage_ip_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(response_t, _impl_.storage_port_)
      + sizeof(response_t::_impl_.storage_port_)
      - PROTOBUF_FIELD_OFFSET(response_t, _impl_.storage_magic_)>(
          reinterpret_cast<char*>(&_impl_.storage_magic_),
          reinterpret_cast<char*>(&other->_impl_.storage_magic_));
}

::google::protobuf::Metadata response_t::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace cm_valid_storage
}  // namespace proto
}  // namespace dfs
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_cm_5fvalid_5fstorage_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
