// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sm_regist.proto
// Protobuf C++ Version: 5.29.2

#ifndef sm_5fregist_2eproto_2epb_2eh
#define sm_5fregist_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_sm_5fregist_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_sm_5fregist_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_sm_5fregist_2eproto;
namespace dfs {
namespace proto {
namespace sm_regist {
class request_t;
struct request_tDefaultTypeInternal;
extern request_tDefaultTypeInternal _request_t_default_instance_;
class response_t;
struct response_tDefaultTypeInternal;
extern response_tDefaultTypeInternal _response_t_default_instance_;
class storage_info_t;
struct storage_info_tDefaultTypeInternal;
extern storage_info_tDefaultTypeInternal _storage_info_t_default_instance_;
}  // namespace sm_regist
}  // namespace proto
}  // namespace dfs
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace dfs {
namespace proto {
namespace sm_regist {

// ===================================================================


// -------------------------------------------------------------------

class storage_info_t final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:dfs.proto.sm_regist.storage_info_t) */ {
 public:
  inline storage_info_t() : storage_info_t(nullptr) {}
  ~storage_info_t() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(storage_info_t* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(storage_info_t));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR storage_info_t(
      ::google::protobuf::internal::ConstantInitialized);

  inline storage_info_t(const storage_info_t& from) : storage_info_t(nullptr, from) {}
  inline storage_info_t(storage_info_t&& from) noexcept
      : storage_info_t(nullptr, std::move(from)) {}
  inline storage_info_t& operator=(const storage_info_t& from) {
    CopyFrom(from);
    return *this;
  }
  inline storage_info_t& operator=(storage_info_t&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const storage_info_t& default_instance() {
    return *internal_default_instance();
  }
  static inline const storage_info_t* internal_default_instance() {
    return reinterpret_cast<const storage_info_t*>(
        &_storage_info_t_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(storage_info_t& a, storage_info_t& b) { a.Swap(&b); }
  inline void Swap(storage_info_t* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(storage_info_t* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  storage_info_t* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<storage_info_t>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const storage_info_t& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const storage_info_t& from) { storage_info_t::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(storage_info_t* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "dfs.proto.sm_regist.storage_info_t"; }

 protected:
  explicit storage_info_t(::google::protobuf::Arena* arena);
  storage_info_t(::google::protobuf::Arena* arena, const storage_info_t& from);
  storage_info_t(::google::protobuf::Arena* arena, storage_info_t&& from) noexcept
      : storage_info_t(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIpFieldNumber = 4,
    kIdFieldNumber = 1,
    kPortFieldNumber = 2,
    kMagicFieldNumber = 3,
  };
  // string ip = 4;
  void clear_ip() ;
  const std::string& ip() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_ip(Arg_&& arg, Args_... args);
  std::string* mutable_ip();
  PROTOBUF_NODISCARD std::string* release_ip();
  void set_allocated_ip(std::string* value);

  private:
  const std::string& _internal_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ip(
      const std::string& value);
  std::string* _internal_mutable_ip();

  public:
  // uint32 id = 1;
  void clear_id() ;
  ::uint32_t id() const;
  void set_id(::uint32_t value);

  private:
  ::uint32_t _internal_id() const;
  void _internal_set_id(::uint32_t value);

  public:
  // uint32 port = 2;
  void clear_port() ;
  ::uint32_t port() const;
  void set_port(::uint32_t value);

  private:
  ::uint32_t _internal_port() const;
  void _internal_set_port(::uint32_t value);

  public:
  // uint32 magic = 3;
  void clear_magic() ;
  ::uint32_t magic() const;
  void set_magic(::uint32_t value);

  private:
  ::uint32_t _internal_magic() const;
  void _internal_set_magic(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:dfs.proto.sm_regist.storage_info_t)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      45, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const storage_info_t& from_msg);
    ::google::protobuf::internal::ArenaStringPtr ip_;
    ::uint32_t id_;
    ::uint32_t port_;
    ::uint32_t magic_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sm_5fregist_2eproto;
};
// -------------------------------------------------------------------

class response_t final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:dfs.proto.sm_regist.response_t) */ {
 public:
  inline response_t() : response_t(nullptr) {}
  ~response_t() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(response_t* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(response_t));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR response_t(
      ::google::protobuf::internal::ConstantInitialized);

  inline response_t(const response_t& from) : response_t(nullptr, from) {}
  inline response_t(response_t&& from) noexcept
      : response_t(nullptr, std::move(from)) {}
  inline response_t& operator=(const response_t& from) {
    CopyFrom(from);
    return *this;
  }
  inline response_t& operator=(response_t&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const response_t& default_instance() {
    return *internal_default_instance();
  }
  static inline const response_t* internal_default_instance() {
    return reinterpret_cast<const response_t*>(
        &_response_t_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(response_t& a, response_t& b) { a.Swap(&b); }
  inline void Swap(response_t* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(response_t* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  response_t* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<response_t>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const response_t& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const response_t& from) { response_t::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(response_t* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "dfs.proto.sm_regist.response_t"; }

 protected:
  explicit response_t(::google::protobuf::Arena* arena);
  response_t(::google::protobuf::Arena* arena, const response_t& from);
  response_t(::google::protobuf::Arena* arena, response_t&& from) noexcept
      : response_t(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStorageInfoFieldNumber = 2,
    kStorageGroupFieldNumber = 1,
  };
  // repeated .dfs.proto.sm_regist.storage_info_t storage_info = 2;
  int storage_info_size() const;
  private:
  int _internal_storage_info_size() const;

  public:
  void clear_storage_info() ;
  ::dfs::proto::sm_regist::storage_info_t* mutable_storage_info(int index);
  ::google::protobuf::RepeatedPtrField<::dfs::proto::sm_regist::storage_info_t>* mutable_storage_info();

  private:
  const ::google::protobuf::RepeatedPtrField<::dfs::proto::sm_regist::storage_info_t>& _internal_storage_info() const;
  ::google::protobuf::RepeatedPtrField<::dfs::proto::sm_regist::storage_info_t>* _internal_mutable_storage_info();
  public:
  const ::dfs::proto::sm_regist::storage_info_t& storage_info(int index) const;
  ::dfs::proto::sm_regist::storage_info_t* add_storage_info();
  const ::google::protobuf::RepeatedPtrField<::dfs::proto::sm_regist::storage_info_t>& storage_info() const;
  // uint32 storage_group = 1;
  void clear_storage_group() ;
  ::uint32_t storage_group() const;
  void set_storage_group(::uint32_t value);

  private:
  ::uint32_t _internal_storage_group() const;
  void _internal_set_storage_group(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:dfs.proto.sm_regist.response_t)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const response_t& from_msg);
    ::google::protobuf::RepeatedPtrField< ::dfs::proto::sm_regist::storage_info_t > storage_info_;
    ::uint32_t storage_group_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sm_5fregist_2eproto;
};
// -------------------------------------------------------------------

class request_t final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:dfs.proto.sm_regist.request_t) */ {
 public:
  inline request_t() : request_t(nullptr) {}
  ~request_t() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(request_t* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(request_t));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR request_t(
      ::google::protobuf::internal::ConstantInitialized);

  inline request_t(const request_t& from) : request_t(nullptr, from) {}
  inline request_t(request_t&& from) noexcept
      : request_t(nullptr, std::move(from)) {}
  inline request_t& operator=(const request_t& from) {
    CopyFrom(from);
    return *this;
  }
  inline request_t& operator=(request_t&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const request_t& default_instance() {
    return *internal_default_instance();
  }
  static inline const request_t* internal_default_instance() {
    return reinterpret_cast<const request_t*>(
        &_request_t_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(request_t& a, request_t& b) { a.Swap(&b); }
  inline void Swap(request_t* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(request_t* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  request_t* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<request_t>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const request_t& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const request_t& from) { request_t::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(request_t* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "dfs.proto.sm_regist.request_t"; }

 protected:
  explicit request_t(::google::protobuf::Arena* arena);
  request_t(::google::protobuf::Arena* arena, const request_t& from);
  request_t(::google::protobuf::Arena* arena, request_t&& from) noexcept
      : request_t(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStorageInfoFieldNumber = 1,
    kMasterMagicFieldNumber = 2,
  };
  // .dfs.proto.sm_regist.storage_info_t storage_info = 1;
  bool has_storage_info() const;
  void clear_storage_info() ;
  const ::dfs::proto::sm_regist::storage_info_t& storage_info() const;
  PROTOBUF_NODISCARD ::dfs::proto::sm_regist::storage_info_t* release_storage_info();
  ::dfs::proto::sm_regist::storage_info_t* mutable_storage_info();
  void set_allocated_storage_info(::dfs::proto::sm_regist::storage_info_t* value);
  void unsafe_arena_set_allocated_storage_info(::dfs::proto::sm_regist::storage_info_t* value);
  ::dfs::proto::sm_regist::storage_info_t* unsafe_arena_release_storage_info();

  private:
  const ::dfs::proto::sm_regist::storage_info_t& _internal_storage_info() const;
  ::dfs::proto::sm_regist::storage_info_t* _internal_mutable_storage_info();

  public:
  // uint32 master_magic = 2;
  void clear_master_magic() ;
  ::uint32_t master_magic() const;
  void set_master_magic(::uint32_t value);

  private:
  ::uint32_t _internal_master_magic() const;
  void _internal_set_master_magic(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:dfs.proto.sm_regist.request_t)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const request_t& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::dfs::proto::sm_regist::storage_info_t* storage_info_;
    ::uint32_t master_magic_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_sm_5fregist_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// storage_info_t

// uint32 id = 1;
inline void storage_info_t::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0u;
}
inline ::uint32_t storage_info_t::id() const {
  // @@protoc_insertion_point(field_get:dfs.proto.sm_regist.storage_info_t.id)
  return _internal_id();
}
inline void storage_info_t::set_id(::uint32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:dfs.proto.sm_regist.storage_info_t.id)
}
inline ::uint32_t storage_info_t::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void storage_info_t::_internal_set_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// uint32 port = 2;
inline void storage_info_t::clear_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = 0u;
}
inline ::uint32_t storage_info_t::port() const {
  // @@protoc_insertion_point(field_get:dfs.proto.sm_regist.storage_info_t.port)
  return _internal_port();
}
inline void storage_info_t::set_port(::uint32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:dfs.proto.sm_regist.storage_info_t.port)
}
inline ::uint32_t storage_info_t::_internal_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.port_;
}
inline void storage_info_t::_internal_set_port(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = value;
}

// uint32 magic = 3;
inline void storage_info_t::clear_magic() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.magic_ = 0u;
}
inline ::uint32_t storage_info_t::magic() const {
  // @@protoc_insertion_point(field_get:dfs.proto.sm_regist.storage_info_t.magic)
  return _internal_magic();
}
inline void storage_info_t::set_magic(::uint32_t value) {
  _internal_set_magic(value);
  // @@protoc_insertion_point(field_set:dfs.proto.sm_regist.storage_info_t.magic)
}
inline ::uint32_t storage_info_t::_internal_magic() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.magic_;
}
inline void storage_info_t::_internal_set_magic(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.magic_ = value;
}

// string ip = 4;
inline void storage_info_t::clear_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_.ClearToEmpty();
}
inline const std::string& storage_info_t::ip() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:dfs.proto.sm_regist.storage_info_t.ip)
  return _internal_ip();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void storage_info_t::set_ip(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:dfs.proto.sm_regist.storage_info_t.ip)
}
inline std::string* storage_info_t::mutable_ip() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_ip();
  // @@protoc_insertion_point(field_mutable:dfs.proto.sm_regist.storage_info_t.ip)
  return _s;
}
inline const std::string& storage_info_t::_internal_ip() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ip_.Get();
}
inline void storage_info_t::_internal_set_ip(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_.Set(value, GetArena());
}
inline std::string* storage_info_t::_internal_mutable_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.ip_.Mutable( GetArena());
}
inline std::string* storage_info_t::release_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:dfs.proto.sm_regist.storage_info_t.ip)
  return _impl_.ip_.Release();
}
inline void storage_info_t::set_allocated_ip(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.ip_.IsDefault()) {
    _impl_.ip_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:dfs.proto.sm_regist.storage_info_t.ip)
}

// -------------------------------------------------------------------

// request_t

// .dfs.proto.sm_regist.storage_info_t storage_info = 1;
inline bool request_t::has_storage_info() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.storage_info_ != nullptr);
  return value;
}
inline void request_t::clear_storage_info() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.storage_info_ != nullptr) _impl_.storage_info_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::dfs::proto::sm_regist::storage_info_t& request_t::_internal_storage_info() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::dfs::proto::sm_regist::storage_info_t* p = _impl_.storage_info_;
  return p != nullptr ? *p : reinterpret_cast<const ::dfs::proto::sm_regist::storage_info_t&>(::dfs::proto::sm_regist::_storage_info_t_default_instance_);
}
inline const ::dfs::proto::sm_regist::storage_info_t& request_t::storage_info() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:dfs.proto.sm_regist.request_t.storage_info)
  return _internal_storage_info();
}
inline void request_t::unsafe_arena_set_allocated_storage_info(::dfs::proto::sm_regist::storage_info_t* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.storage_info_);
  }
  _impl_.storage_info_ = reinterpret_cast<::dfs::proto::sm_regist::storage_info_t*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:dfs.proto.sm_regist.request_t.storage_info)
}
inline ::dfs::proto::sm_regist::storage_info_t* request_t::release_storage_info() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::dfs::proto::sm_regist::storage_info_t* released = _impl_.storage_info_;
  _impl_.storage_info_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::dfs::proto::sm_regist::storage_info_t* request_t::unsafe_arena_release_storage_info() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:dfs.proto.sm_regist.request_t.storage_info)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::dfs::proto::sm_regist::storage_info_t* temp = _impl_.storage_info_;
  _impl_.storage_info_ = nullptr;
  return temp;
}
inline ::dfs::proto::sm_regist::storage_info_t* request_t::_internal_mutable_storage_info() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.storage_info_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::dfs::proto::sm_regist::storage_info_t>(GetArena());
    _impl_.storage_info_ = reinterpret_cast<::dfs::proto::sm_regist::storage_info_t*>(p);
  }
  return _impl_.storage_info_;
}
inline ::dfs::proto::sm_regist::storage_info_t* request_t::mutable_storage_info() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::dfs::proto::sm_regist::storage_info_t* _msg = _internal_mutable_storage_info();
  // @@protoc_insertion_point(field_mutable:dfs.proto.sm_regist.request_t.storage_info)
  return _msg;
}
inline void request_t::set_allocated_storage_info(::dfs::proto::sm_regist::storage_info_t* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.storage_info_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.storage_info_ = reinterpret_cast<::dfs::proto::sm_regist::storage_info_t*>(value);
  // @@protoc_insertion_point(field_set_allocated:dfs.proto.sm_regist.request_t.storage_info)
}

// uint32 master_magic = 2;
inline void request_t::clear_master_magic() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.master_magic_ = 0u;
}
inline ::uint32_t request_t::master_magic() const {
  // @@protoc_insertion_point(field_get:dfs.proto.sm_regist.request_t.master_magic)
  return _internal_master_magic();
}
inline void request_t::set_master_magic(::uint32_t value) {
  _internal_set_master_magic(value);
  // @@protoc_insertion_point(field_set:dfs.proto.sm_regist.request_t.master_magic)
}
inline ::uint32_t request_t::_internal_master_magic() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.master_magic_;
}
inline void request_t::_internal_set_master_magic(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.master_magic_ = value;
}

// -------------------------------------------------------------------

// response_t

// uint32 storage_group = 1;
inline void response_t::clear_storage_group() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.storage_group_ = 0u;
}
inline ::uint32_t response_t::storage_group() const {
  // @@protoc_insertion_point(field_get:dfs.proto.sm_regist.response_t.storage_group)
  return _internal_storage_group();
}
inline void response_t::set_storage_group(::uint32_t value) {
  _internal_set_storage_group(value);
  // @@protoc_insertion_point(field_set:dfs.proto.sm_regist.response_t.storage_group)
}
inline ::uint32_t response_t::_internal_storage_group() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.storage_group_;
}
inline void response_t::_internal_set_storage_group(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.storage_group_ = value;
}

// repeated .dfs.proto.sm_regist.storage_info_t storage_info = 2;
inline int response_t::_internal_storage_info_size() const {
  return _internal_storage_info().size();
}
inline int response_t::storage_info_size() const {
  return _internal_storage_info_size();
}
inline void response_t::clear_storage_info() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.storage_info_.Clear();
}
inline ::dfs::proto::sm_regist::storage_info_t* response_t::mutable_storage_info(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:dfs.proto.sm_regist.response_t.storage_info)
  return _internal_mutable_storage_info()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::dfs::proto::sm_regist::storage_info_t>* response_t::mutable_storage_info()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:dfs.proto.sm_regist.response_t.storage_info)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_storage_info();
}
inline const ::dfs::proto::sm_regist::storage_info_t& response_t::storage_info(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:dfs.proto.sm_regist.response_t.storage_info)
  return _internal_storage_info().Get(index);
}
inline ::dfs::proto::sm_regist::storage_info_t* response_t::add_storage_info() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::dfs::proto::sm_regist::storage_info_t* _add = _internal_mutable_storage_info()->Add();
  // @@protoc_insertion_point(field_add:dfs.proto.sm_regist.response_t.storage_info)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::dfs::proto::sm_regist::storage_info_t>& response_t::storage_info() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:dfs.proto.sm_regist.response_t.storage_info)
  return _internal_storage_info();
}
inline const ::google::protobuf::RepeatedPtrField<::dfs::proto::sm_regist::storage_info_t>&
response_t::_internal_storage_info() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.storage_info_;
}
inline ::google::protobuf::RepeatedPtrField<::dfs::proto::sm_regist::storage_info_t>*
response_t::_internal_mutable_storage_info() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.storage_info_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace sm_regist
}  // namespace proto
}  // namespace dfs


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // sm_5fregist_2eproto_2epb_2eh
