// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sm_regist.proto
// Protobuf C++ Version: 5.29.2

#include "sm_regist.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace dfs {
namespace proto {
namespace sm_regist {

inline constexpr storage_info_t::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : ip_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0u},
        port_{0u},
        magic_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR storage_info_t::storage_info_t(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct storage_info_tDefaultTypeInternal {
  PROTOBUF_CONSTEXPR storage_info_tDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~storage_info_tDefaultTypeInternal() {}
  union {
    storage_info_t _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 storage_info_tDefaultTypeInternal _storage_info_t_default_instance_;

inline constexpr response_t::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : storage_info_{},
        storage_group_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR response_t::response_t(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct response_tDefaultTypeInternal {
  PROTOBUF_CONSTEXPR response_tDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~response_tDefaultTypeInternal() {}
  union {
    response_t _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 response_tDefaultTypeInternal _response_t_default_instance_;

inline constexpr request_t::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        storage_info_{nullptr},
        master_magic_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR request_t::request_t(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct request_tDefaultTypeInternal {
  PROTOBUF_CONSTEXPR request_tDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~request_tDefaultTypeInternal() {}
  union {
    request_t _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 request_tDefaultTypeInternal _request_t_default_instance_;
}  // namespace sm_regist
}  // namespace proto
}  // namespace dfs
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_sm_5fregist_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_sm_5fregist_2eproto = nullptr;
const ::uint32_t
    TableStruct_sm_5fregist_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::dfs::proto::sm_regist::storage_info_t, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::dfs::proto::sm_regist::storage_info_t, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::dfs::proto::sm_regist::storage_info_t, _impl_.port_),
        PROTOBUF_FIELD_OFFSET(::dfs::proto::sm_regist::storage_info_t, _impl_.magic_),
        PROTOBUF_FIELD_OFFSET(::dfs::proto::sm_regist::storage_info_t, _impl_.ip_),
        PROTOBUF_FIELD_OFFSET(::dfs::proto::sm_regist::request_t, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::dfs::proto::sm_regist::request_t, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::dfs::proto::sm_regist::request_t, _impl_.storage_info_),
        PROTOBUF_FIELD_OFFSET(::dfs::proto::sm_regist::request_t, _impl_.master_magic_),
        0,
        ~0u,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::dfs::proto::sm_regist::response_t, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::dfs::proto::sm_regist::response_t, _impl_.storage_group_),
        PROTOBUF_FIELD_OFFSET(::dfs::proto::sm_regist::response_t, _impl_.storage_info_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::dfs::proto::sm_regist::storage_info_t)},
        {12, 22, -1, sizeof(::dfs::proto::sm_regist::request_t)},
        {24, -1, -1, sizeof(::dfs::proto::sm_regist::response_t)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::dfs::proto::sm_regist::_storage_info_t_default_instance_._instance,
    &::dfs::proto::sm_regist::_request_t_default_instance_._instance,
    &::dfs::proto::sm_regist::_response_t_default_instance_._instance,
};
const char descriptor_table_protodef_sm_5fregist_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017sm_regist.proto\022\023dfs.proto.sm_regist\"E"
    "\n\016storage_info_t\022\n\n\002id\030\001 \001(\r\022\014\n\004port\030\002 \001"
    "(\r\022\r\n\005magic\030\003 \001(\r\022\n\n\002ip\030\004 \001(\t\"\\\n\trequest"
    "_t\0229\n\014storage_info\030\001 \001(\0132#.dfs.proto.sm_"
    "regist.storage_info_t\022\024\n\014master_magic\030\002 "
    "\001(\r\"^\n\nresponse_t\022\025\n\rstorage_group\030\001 \001(\r"
    "\0229\n\014storage_info\030\002 \003(\0132#.dfs.proto.sm_re"
    "gist.storage_info_tb\006proto3"
};
static ::absl::once_flag descriptor_table_sm_5fregist_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_sm_5fregist_2eproto = {
    false,
    false,
    307,
    descriptor_table_protodef_sm_5fregist_2eproto,
    "sm_regist.proto",
    &descriptor_table_sm_5fregist_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_sm_5fregist_2eproto::offsets,
    file_level_enum_descriptors_sm_5fregist_2eproto,
    file_level_service_descriptors_sm_5fregist_2eproto,
};
namespace dfs {
namespace proto {
namespace sm_regist {
// ===================================================================

class storage_info_t::_Internal {
 public:
};

storage_info_t::storage_info_t(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:dfs.proto.sm_regist.storage_info_t)
}
inline PROTOBUF_NDEBUG_INLINE storage_info_t::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::dfs::proto::sm_regist::storage_info_t& from_msg)
      : ip_(arena, from.ip_),
        _cached_size_{0} {}

storage_info_t::storage_info_t(
    ::google::protobuf::Arena* arena,
    const storage_info_t& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  storage_info_t* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, magic_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::magic_));

  // @@protoc_insertion_point(copy_constructor:dfs.proto.sm_regist.storage_info_t)
}
inline PROTOBUF_NDEBUG_INLINE storage_info_t::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : ip_(arena),
        _cached_size_{0} {}

inline void storage_info_t::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, magic_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::magic_));
}
storage_info_t::~storage_info_t() {
  // @@protoc_insertion_point(destructor:dfs.proto.sm_regist.storage_info_t)
  SharedDtor(*this);
}
inline void storage_info_t::SharedDtor(MessageLite& self) {
  storage_info_t& this_ = static_cast<storage_info_t&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.ip_.Destroy();
  this_._impl_.~Impl_();
}

inline void* storage_info_t::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) storage_info_t(arena);
}
constexpr auto storage_info_t::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(storage_info_t),
                                            alignof(storage_info_t));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull storage_info_t::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_storage_info_t_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &storage_info_t::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<storage_info_t>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &storage_info_t::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<storage_info_t>(), &storage_info_t::ByteSizeLong,
            &storage_info_t::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(storage_info_t, _impl_._cached_size_),
        false,
    },
    &storage_info_t::kDescriptorMethods,
    &descriptor_table_sm_5fregist_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* storage_info_t::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 45, 2> storage_info_t::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::dfs::proto::sm_regist::storage_info_t>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string ip = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(storage_info_t, _impl_.ip_)}},
    // uint32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(storage_info_t, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(storage_info_t, _impl_.id_)}},
    // uint32 port = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(storage_info_t, _impl_.port_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(storage_info_t, _impl_.port_)}},
    // uint32 magic = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(storage_info_t, _impl_.magic_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(storage_info_t, _impl_.magic_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 id = 1;
    {PROTOBUF_FIELD_OFFSET(storage_info_t, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 port = 2;
    {PROTOBUF_FIELD_OFFSET(storage_info_t, _impl_.port_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 magic = 3;
    {PROTOBUF_FIELD_OFFSET(storage_info_t, _impl_.magic_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // string ip = 4;
    {PROTOBUF_FIELD_OFFSET(storage_info_t, _impl_.ip_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\42\0\0\0\2\0\0\0"
    "dfs.proto.sm_regist.storage_info_t"
    "ip"
  }},
};

PROTOBUF_NOINLINE void storage_info_t::Clear() {
// @@protoc_insertion_point(message_clear_start:dfs.proto.sm_regist.storage_info_t)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ip_.ClearToEmpty();
  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.magic_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.magic_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* storage_info_t::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const storage_info_t& this_ = static_cast<const storage_info_t&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* storage_info_t::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const storage_info_t& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:dfs.proto.sm_regist.storage_info_t)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 id = 1;
          if (this_._internal_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_id(), target);
          }

          // uint32 port = 2;
          if (this_._internal_port() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_port(), target);
          }

          // uint32 magic = 3;
          if (this_._internal_magic() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                3, this_._internal_magic(), target);
          }

          // string ip = 4;
          if (!this_._internal_ip().empty()) {
            const std::string& _s = this_._internal_ip();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "dfs.proto.sm_regist.storage_info_t.ip");
            target = stream->WriteStringMaybeAliased(4, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:dfs.proto.sm_regist.storage_info_t)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t storage_info_t::ByteSizeLong(const MessageLite& base) {
          const storage_info_t& this_ = static_cast<const storage_info_t&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t storage_info_t::ByteSizeLong() const {
          const storage_info_t& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:dfs.proto.sm_regist.storage_info_t)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string ip = 4;
            if (!this_._internal_ip().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_ip());
            }
            // uint32 id = 1;
            if (this_._internal_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_id());
            }
            // uint32 port = 2;
            if (this_._internal_port() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_port());
            }
            // uint32 magic = 3;
            if (this_._internal_magic() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_magic());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void storage_info_t::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<storage_info_t*>(&to_msg);
  auto& from = static_cast<const storage_info_t&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dfs.proto.sm_regist.storage_info_t)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_ip().empty()) {
    _this->_internal_set_ip(from._internal_ip());
  }
  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  if (from._internal_port() != 0) {
    _this->_impl_.port_ = from._impl_.port_;
  }
  if (from._internal_magic() != 0) {
    _this->_impl_.magic_ = from._impl_.magic_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void storage_info_t::CopyFrom(const storage_info_t& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dfs.proto.sm_regist.storage_info_t)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void storage_info_t::InternalSwap(storage_info_t* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ip_, &other->_impl_.ip_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(storage_info_t, _impl_.magic_)
      + sizeof(storage_info_t::_impl_.magic_)
      - PROTOBUF_FIELD_OFFSET(storage_info_t, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata storage_info_t::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class request_t::_Internal {
 public:
  using HasBits =
      decltype(std::declval<request_t>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(request_t, _impl_._has_bits_);
};

request_t::request_t(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:dfs.proto.sm_regist.request_t)
}
inline PROTOBUF_NDEBUG_INLINE request_t::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::dfs::proto::sm_regist::request_t& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

request_t::request_t(
    ::google::protobuf::Arena* arena,
    const request_t& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  request_t* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.storage_info_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::dfs::proto::sm_regist::storage_info_t>(
                              arena, *from._impl_.storage_info_)
                        : nullptr;
  _impl_.master_magic_ = from._impl_.master_magic_;

  // @@protoc_insertion_point(copy_constructor:dfs.proto.sm_regist.request_t)
}
inline PROTOBUF_NDEBUG_INLINE request_t::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void request_t::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, storage_info_),
           0,
           offsetof(Impl_, master_magic_) -
               offsetof(Impl_, storage_info_) +
               sizeof(Impl_::master_magic_));
}
request_t::~request_t() {
  // @@protoc_insertion_point(destructor:dfs.proto.sm_regist.request_t)
  SharedDtor(*this);
}
inline void request_t::SharedDtor(MessageLite& self) {
  request_t& this_ = static_cast<request_t&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.storage_info_;
  this_._impl_.~Impl_();
}

inline void* request_t::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) request_t(arena);
}
constexpr auto request_t::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(request_t),
                                            alignof(request_t));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull request_t::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_request_t_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &request_t::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<request_t>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &request_t::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<request_t>(), &request_t::ByteSizeLong,
            &request_t::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(request_t, _impl_._cached_size_),
        false,
    },
    &request_t::kDescriptorMethods,
    &descriptor_table_sm_5fregist_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* request_t::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> request_t::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(request_t, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::dfs::proto::sm_regist::request_t>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 master_magic = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(request_t, _impl_.master_magic_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(request_t, _impl_.master_magic_)}},
    // .dfs.proto.sm_regist.storage_info_t storage_info = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(request_t, _impl_.storage_info_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .dfs.proto.sm_regist.storage_info_t storage_info = 1;
    {PROTOBUF_FIELD_OFFSET(request_t, _impl_.storage_info_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // uint32 master_magic = 2;
    {PROTOBUF_FIELD_OFFSET(request_t, _impl_.master_magic_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }}, {{
    {::_pbi::TcParser::GetTable<::dfs::proto::sm_regist::storage_info_t>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void request_t::Clear() {
// @@protoc_insertion_point(message_clear_start:dfs.proto.sm_regist.request_t)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.storage_info_ != nullptr);
    _impl_.storage_info_->Clear();
  }
  _impl_.master_magic_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* request_t::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const request_t& this_ = static_cast<const request_t&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* request_t::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const request_t& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:dfs.proto.sm_regist.request_t)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .dfs.proto.sm_regist.storage_info_t storage_info = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.storage_info_, this_._impl_.storage_info_->GetCachedSize(), target,
                stream);
          }

          // uint32 master_magic = 2;
          if (this_._internal_master_magic() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_master_magic(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:dfs.proto.sm_regist.request_t)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t request_t::ByteSizeLong(const MessageLite& base) {
          const request_t& this_ = static_cast<const request_t&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t request_t::ByteSizeLong() const {
          const request_t& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:dfs.proto.sm_regist.request_t)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .dfs.proto.sm_regist.storage_info_t storage_info = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.storage_info_);
            }
          }
           {
            // uint32 master_magic = 2;
            if (this_._internal_master_magic() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_master_magic());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void request_t::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<request_t*>(&to_msg);
  auto& from = static_cast<const request_t&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:dfs.proto.sm_regist.request_t)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.storage_info_ != nullptr);
    if (_this->_impl_.storage_info_ == nullptr) {
      _this->_impl_.storage_info_ =
          ::google::protobuf::Message::CopyConstruct<::dfs::proto::sm_regist::storage_info_t>(arena, *from._impl_.storage_info_);
    } else {
      _this->_impl_.storage_info_->MergeFrom(*from._impl_.storage_info_);
    }
  }
  if (from._internal_master_magic() != 0) {
    _this->_impl_.master_magic_ = from._impl_.master_magic_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void request_t::CopyFrom(const request_t& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dfs.proto.sm_regist.request_t)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void request_t::InternalSwap(request_t* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(request_t, _impl_.master_magic_)
      + sizeof(request_t::_impl_.master_magic_)
      - PROTOBUF_FIELD_OFFSET(request_t, _impl_.storage_info_)>(
          reinterpret_cast<char*>(&_impl_.storage_info_),
          reinterpret_cast<char*>(&other->_impl_.storage_info_));
}

::google::protobuf::Metadata request_t::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class response_t::_Internal {
 public:
};

response_t::response_t(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:dfs.proto.sm_regist.response_t)
}
inline PROTOBUF_NDEBUG_INLINE response_t::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::dfs::proto::sm_regist::response_t& from_msg)
      : storage_info_{visibility, arena, from.storage_info_},
        _cached_size_{0} {}

response_t::response_t(
    ::google::protobuf::Arena* arena,
    const response_t& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  response_t* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.storage_group_ = from._impl_.storage_group_;

  // @@protoc_insertion_point(copy_constructor:dfs.proto.sm_regist.response_t)
}
inline PROTOBUF_NDEBUG_INLINE response_t::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : storage_info_{visibility, arena},
        _cached_size_{0} {}

inline void response_t::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.storage_group_ = {};
}
response_t::~response_t() {
  // @@protoc_insertion_point(destructor:dfs.proto.sm_regist.response_t)
  SharedDtor(*this);
}
inline void response_t::SharedDtor(MessageLite& self) {
  response_t& this_ = static_cast<response_t&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* response_t::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) response_t(arena);
}
constexpr auto response_t::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(response_t, _impl_.storage_info_) +
          decltype(response_t::_impl_.storage_info_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(response_t), alignof(response_t), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&response_t::PlacementNew_,
                                 sizeof(response_t),
                                 alignof(response_t));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull response_t::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_response_t_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &response_t::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<response_t>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &response_t::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<response_t>(), &response_t::ByteSizeLong,
            &response_t::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(response_t, _impl_._cached_size_),
        false,
    },
    &response_t::kDescriptorMethods,
    &descriptor_table_sm_5fregist_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* response_t::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> response_t::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::dfs::proto::sm_regist::response_t>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .dfs.proto.sm_regist.storage_info_t storage_info = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(response_t, _impl_.storage_info_)}},
    // uint32 storage_group = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(response_t, _impl_.storage_group_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(response_t, _impl_.storage_group_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 storage_group = 1;
    {PROTOBUF_FIELD_OFFSET(response_t, _impl_.storage_group_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // repeated .dfs.proto.sm_regist.storage_info_t storage_info = 2;
    {PROTOBUF_FIELD_OFFSET(response_t, _impl_.storage_info_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::dfs::proto::sm_regist::storage_info_t>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void response_t::Clear() {
// @@protoc_insertion_point(message_clear_start:dfs.proto.sm_regist.response_t)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.storage_info_.Clear();
  _impl_.storage_group_ = 0u;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* response_t::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const response_t& this_ = static_cast<const response_t&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* response_t::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const response_t& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:dfs.proto.sm_regist.response_t)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 storage_group = 1;
          if (this_._internal_storage_group() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_storage_group(), target);
          }

          // repeated .dfs.proto.sm_regist.storage_info_t storage_info = 2;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_storage_info_size());
               i < n; i++) {
            const auto& repfield = this_._internal_storage_info().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    2, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:dfs.proto.sm_regist.response_t)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t response_t::ByteSizeLong(const MessageLite& base) {
          const response_t& this_ = static_cast<const response_t&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t response_t::ByteSizeLong() const {
          const response_t& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:dfs.proto.sm_regist.response_t)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .dfs.proto.sm_regist.storage_info_t storage_info = 2;
            {
              total_size += 1UL * this_._internal_storage_info_size();
              for (const auto& msg : this_._internal_storage_info()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // uint32 storage_group = 1;
            if (this_._internal_storage_group() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_storage_group());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void response_t::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<response_t*>(&to_msg);
  auto& from = static_cast<const response_t&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dfs.proto.sm_regist.response_t)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_storage_info()->MergeFrom(
      from._internal_storage_info());
  if (from._internal_storage_group() != 0) {
    _this->_impl_.storage_group_ = from._impl_.storage_group_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void response_t::CopyFrom(const response_t& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dfs.proto.sm_regist.response_t)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void response_t::InternalSwap(response_t* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.storage_info_.InternalSwap(&other->_impl_.storage_info_);
        swap(_impl_.storage_group_, other->_impl_.storage_group_);
}

::google::protobuf::Metadata response_t::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace sm_regist
}  // namespace proto
}  // namespace dfs
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_sm_5fregist_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
